theme: minima
title: David Veitch's Website
description: A showcase of some of my work
twitter_username: daveveitch
github_username:  daveveitch
linkedin_username: dveitch
header_pages:
  - about.md
  - blog.md
  - contact.md
  - projects.md
  - mathproblems.md
